<?php
namespace App\Controllers;

use App\Helpers\BaseController;
use App\Helpers\Session;
use App\Helpers\Database;

class InstallController extends BaseController
{
    public function index(): void
    {
        if (file_exists(CONFIG_PATH . '/installed.lock')) {
            $this->redirect('/');
        }
        $this->view('install/index', ['pageTitle' => 'HEMS Core Installation Wizard'], null);
    }

    public function step1(): void
    {
        // Database Setup
        $host = trim($_POST['host'] ?? '127.0.0.1');
        $port = (int)($_POST['port'] ?? 3306);
        $dbname = trim($_POST['database'] ?? 'hems_db');
        $username = trim($_POST['username'] ?? 'root');
        $password = $_POST['password'] ?? '';

        $config = [
            'driver'    => 'mysql',
            'host'      => $host,
            'port'      => $port,
            'database'  => $dbname,
            'username'  => $username,
            'password'  => $password,
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
            'options'   => [
                \PDO::ATTR_ERRMODE            => \PDO::ERRMODE_EXCEPTION,
                \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_OBJ,
                \PDO::ATTR_EMULATE_PREPARES   => false,
            ]
        ];

        // Test connection (without database first to create if needed)
        try {
            $dsn = "mysql:host={$host};port={$port};charset=utf8mb4";
            $pdo = new \PDO($dsn, $username, $password, [\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION]);
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbname}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        } catch (\PDOException $e) {
            $this->json(['success' => false, 'message' => 'Database connection failed: ' . $e->getMessage()]);
            return;
        }

        // Test connection with the database
        if (!Database::testConnection($config)) {
            $this->json(['success' => false, 'message' => 'Unable to connect to the newly created/existing database.']);
            return;
        }

        // Save config file
        $content = "<?php\n/**\n * Database Configuration\n * Generated by Installer\n */\n\nreturn " . var_export($config, true) . ";\n";
        if (file_put_contents(CONFIG_PATH . '/database.php', $content) === false) {
            $this->json(['success' => false, 'message' => 'Failed to write config/database.php. Check permissions.']);
            return;
        }

        $this->json(['success' => true, 'message' => 'Database configured successfully.']);
    }

    public function step2(): void
    {
        // Run migrations and seeds
        $dbConfigPath = CONFIG_PATH . '/database.php';
        if (!file_exists($dbConfigPath)) {
            $this->json(['success' => false, 'message' => 'Database configuration not found. Please complete Step 1.']);
            return;
        }

        $dbConfig = require $dbConfigPath;
        try {
            Database::init($dbConfig);
            $db = Database::getInstance();
            $pdo = $db->getPdo();

            // Load schema
            $schemaFile = ROOT_PATH . '/database/migrations/schema.sql';
            if (!file_exists($schemaFile)) {
                $this->json(['success' => false, 'message' => 'schema.sql not found at ' . $schemaFile]);
                return;
            }
            $schemaSql = file_get_contents($schemaFile);
            $pdo->exec($schemaSql);

            // Load seeds
            $seedsFile = ROOT_PATH . '/database/seeds/sample_data.sql';
            if (!file_exists($seedsFile)) {
                $this->json(['success' => false, 'message' => 'sample_data.sql not found at ' . $seedsFile]);
                return;
            }
            $seedsSql = file_get_contents($seedsFile);
            $pdo->exec($seedsSql);

            $this->json(['success' => true, 'message' => 'Database tables and sample data seeded successfully.']);
        } catch (\Exception $e) {
            $this->json(['success' => false, 'message' => 'Migration/Seeding failed: ' . $e->getMessage()]);
        }
    }

    public function step3(): void
    {
        // Create Admin & App Setup
        $adminEmail = trim($_POST['admin_email'] ?? '');
        $adminPass = $_POST['admin_password'] ?? '';
        $adminFirstName = trim($_POST['admin_first_name'] ?? 'System');
        $adminLastName = trim($_POST['admin_last_name'] ?? 'Admin');
        
        $appName = trim($_POST['app_name'] ?? 'HEMS Core');
        $appUrl = trim($_POST['app_url'] ?? 'http://localhost/hms');

        if (empty($adminEmail) || empty($adminPass)) {
            $this->json(['success' => false, 'message' => 'Admin email and password are required.']);
            return;
        }

        $dbConfigPath = CONFIG_PATH . '/database.php';
        if (!file_exists($dbConfigPath)) {
            $this->json(['success' => false, 'message' => 'Database configuration missing.']);
            return;
        }

        $dbConfig = require $dbConfigPath;
        try {
            Database::init($dbConfig);
            $db = Database::getInstance();

            // Hash the password
            $hashedPassword = password_hash($adminPass, PASSWORD_BCRYPT, ['cost' => 12]);

            // Update default admin user or create a new one
            // We search if the admin user exists in DB from sample data
            $existing = $db->fetch("SELECT id FROM users WHERE id = 1");
            if ($existing) {
                $db->update('users', [
                    'first_name' => $adminFirstName,
                    'last_name'  => $adminLastName,
                    'email'      => $adminEmail,
                    'password'   => $hashedPassword,
                    'status'     => 'active'
                ], 'id = 1');
            } else {
                $userId = $db->insert('users', [
                    'first_name' => $adminFirstName,
                    'last_name'  => $adminLastName,
                    'email'      => $adminEmail,
                    'password'   => $hashedPassword,
                    'status'     => 'active',
                    'job_title'  => 'Super Administrator'
                ]);
                $db->insert('user_roles', [
                    'user_id' => $userId,
                    'role_id' => 8 // Super Administrator role id
                ]);
            }

            // Save App Config changes
            $appConfig = require CONFIG_PATH . '/app.php';
            $appConfig['name'] = $appName;
            $appConfig['url'] = $appUrl;

            $appConfigContent = "<?php\n/**\n * Application Configuration\n * Generated by Installer\n */\n\nreturn " . var_export($appConfig, true) . ";\n";
            file_put_contents(CONFIG_PATH . '/app.php', $appConfigContent);

            $this->json(['success' => true, 'message' => 'Admin account and application configuration saved.']);
        } catch (\Exception $e) {
            $this->json(['success' => false, 'message' => 'Configuration failed: ' . $e->getMessage()]);
        }
    }

    public function finish(): void
    {
        if (file_exists(CONFIG_PATH . '/database.php')) {
            file_put_contents(CONFIG_PATH . '/installed.lock', date('Y-m-d H:i:s'));
            Session::flash('success', 'Installation completed successfully! Welcome to HEMS.');
            $this->redirect('/login');
        } else {
            Session::flash('error', 'Installation not completed yet.');
            $this->redirect('/install');
        }
    }
}
